- name: restart edges
  hosts: all

  tasks:

    - name: Get container info
      docker_container_info:
        name: config_router_1
      register: result

    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Print the status of the container
      debug:
        msg: "The container status is {{ result.container['State']['Status'] }}, since {{ result.container['Created'] }}"
      when: result.exists

    - name: Restart container router
      docker_container:
        name: config_router_1
        state: started
        restart: yes

    - name: Get container info after restart
      docker_container_info:
        name: config_router_1
      register: result2

    - name: Print the status of the container after restart
      debug:
        msg: "The container status is {{ result.container['State']['Status'] }}, since {{ result.container['Created'] }}"
      when: result2.exists

    - name: Delete Backup KEY
      shell: rm -rf /etc/cyolo/certs/key.pem.backup
      loop_control:
          pause: 120
